spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    locations: classpath:db/migration
  r2dbc:
    pool:
      initial-size: 2
      max-size: 10
      max-idle-time: 30m
      max-life-time: 60m
logging:
  level:
    io.r2dbc.pool: ${R2DBC_POOL_LOG_LEVEL:WARN}
    io.r2dbc.postgresql: ${R2DBC_POSTGRES_LOG_LEVEL:WARN}
    org.misarch.discount: ${DISCOUNT_LOG_LEVEL:WARN}
management:
  endpoints:
    web:
      base-path: /
graphql:
  packages: org.misarch.discount
  federation:
    enabled: true